'use client';

import {
  useMemo,
  useState,
  type ChangeEvent,
  type DragEvent,
  type FormEvent,
  type ReactNode,
} from 'react';
import type { CSSProperties } from 'react';
import Link from 'next/link';
import {
  ArrowRight,
  Check,
  ChevronDown,
  FileText,
  Globe2,
  Headphones,
  HelpCircle,
  Info,
  LifeBuoy,
  Paperclip,
  Phone,
  ShieldCheck,
  Upload,
  UsersRound,
  type LucideIcon,
} from 'lucide-react';
import { motion } from 'framer-motion';

/*
 * TRYVION — CUSTOMER SUPPORT
 *
 * Route:
 * /contact/customer-support
 *
 * The page intentionally does NOT render Header, Footer or the
 * SiteThemeProvider. The existing TRYVION root application shell
 * supplies those globally, matching the Sales Enquiries and RFP
 * page architecture.
 *
 * Uploads:
 * Files are uploaded directly to the private TRYVION Blob store
 * through a short-lived presigned PUT URL generated by the CMS.
 *
 * Submission:
 * POST /api/customer-support
 */

const HERO_IMAGE = '/images/customer-support-hero.png';

const SUPPORT_AREAS = [
  'SAP Applications',
  'AI & Automation',
  'Integration & Technology',
  'Operate',
  'Other Enquiry',
] as const;

const SUPPORT_PRIORITIES = ['Low', 'Medium', 'High', 'Critical / Urgent'] as const;

const MAX_FILE_SIZE = 2 * 1024 * 1024;
const MAX_FILES = 5;

const ALLOWED_FILE_EXTENSIONS = new Set([
  'pdf',
  'doc',
  'docx',
  'xls',
  'xlsx',
  'txt',
  'png',
  'jpg',
  'jpeg',
  'zip',
]);

const CONTENT_TYPE_BY_EXTENSION: Record<string, string> = {
  pdf: 'application/pdf',
  doc: 'application/msword',
  docx: 'application/vnd.openxmlformats-officedocument.wordprocessingml.document',
  xls: 'application/vnd.ms-excel',
  xlsx: 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',
  txt: 'text/plain',
  png: 'image/png',
  jpg: 'image/jpeg',
  jpeg: 'image/jpeg',
  zip: 'application/zip',
};

const HERO_POINTS = [
  {
    title: 'Expert assistance',
    body: 'Get help from the right support specialists.',
    icon: Headphones,
  },
  {
    title: 'Timely response',
    body: 'We prioritise and respond as quickly as possible.',
    icon: LifeBuoy,
  },
  {
    title: 'Reliable support',
    body: 'Count on us to keep your business running.',
    icon: ShieldCheck,
  },
] as const;

const HELP_ITEMS = [
  {
    title: 'SAP Applications',
    body: 'S/4HANA, SuccessFactors, BTP and other SAP applications.',
    icon: FileText,
  },
  {
    title: 'AI & Automation',
    body: 'AI solutions, intelligent automation and AI platforms.',
    icon: LifeBuoy,
  },
  {
    title: 'Integration & Technology',
    body: 'Integration, APIs, middleware and enterprise technology platforms.',
    icon: Globe2,
  },
  {
    title: 'Operate',
    body: 'Application support, system operations and managed services.',
    icon: ShieldCheck,
  },
  {
    title: 'Other Enquiry',
    body: 'General questions or other support related assistance.',
    icon: HelpCircle,
  },
] as const;

const TRUST_ITEMS = [
  {
    title: 'Experienced Experts',
    body: 'Certified professionals with in-depth product knowledge.',
    icon: ShieldCheck,
  },
  {
    title: 'Global Support',
    body: 'Support across time zones and multiple delivery centers.',
    icon: Globe2,
  },
  {
    title: 'Proactive Approach',
    body: 'We monitor, analyse and help prevent issues early.',
    icon: LifeBuoy,
  },
  {
    title: 'Customer Focused',
    body: 'Your success is our priority — always.',
    icon: UsersRound,
  },
] as const;

type FormState = {
  fullName: string;
  company: string;
  workEmail: string;
  phone: string;
  supportArea: string;
  supportPriority: string;
  customerProjectReference: string;
  issue: string;
  privacyConsent: boolean;
  marketingConsent: boolean;
  website: string;
};

type UploadedDocument = {
  id: string;
  fileName: string;
  blobPathname: string;
  contentType: string;
  fileSize: number;
};

const INITIAL_FORM: FormState = {
  fullName: '',
  company: '',
  workEmail: '',
  phone: '',
  supportArea: '',
  supportPriority: '',
  customerProjectReference: '',
  issue: '',
  privacyConsent: false,
  marketingConsent: false,
  website: '',
};

const inputStyle = {
  width: '100%',
  height: 46,
  border: '1px solid var(--border-default)',
  borderRadius: 'var(--radius-xs)',
  background: 'var(--surface-default)',
  color: 'var(--content-primary)',
  padding: '0 0.85rem',
  outline: 'none',
  fontFamily: 'var(--family-text)',
  fontSize: '0.875rem',
  boxSizing: 'border-box' as const,
};

function FieldLabel({ children, required = false }: { children: ReactNode; required?: boolean }) {
  return (
    <label
      style={{
        display: 'block',
        marginBottom: '0.5rem',
        color: 'var(--content-primary)',
        fontSize: '0.78rem',
        fontWeight: 700,
        lineHeight: 1.4,
      }}
    >
      {children}
      {required && (
        <span
          aria-hidden="true"
          style={{
            color: 'var(--content-accent)',
            marginLeft: 3,
          }}
        >
          *
        </span>
      )}
    </label>
  );
}

function TextInput({
  label,
  required,
  value,
  onChange,
  placeholder,
  type = 'text',
}: {
  label: string;
  required?: boolean;
  value: string;
  onChange: (value: string) => void;
  placeholder?: string;
  type?: string;
}) {
  return (
    <div>
      <FieldLabel required={required}>{label}</FieldLabel>
      <input
        type={type}
        value={value}
        onChange={(event) => onChange(event.target.value)}
        placeholder={placeholder}
        required={required}
        style={inputStyle}
      />
    </div>
  );
}

function SelectInput({
  label,
  required,
  value,
  onChange,
  options,
  placeholder = 'Select an option',
}: {
  label: string;
  required?: boolean;
  value: string;
  onChange: (value: string) => void;
  options: readonly string[];
  placeholder?: string;
}) {
  return (
    <div>
      <FieldLabel required={required}>{label}</FieldLabel>
      <div style={{ position: 'relative' }}>
        <select
          value={value}
          onChange={(event) => onChange(event.target.value)}
          required={required}
          style={{
            ...inputStyle,
            appearance: 'none',
            paddingRight: '2.7rem',
          }}
        >
          <option value="">{placeholder}</option>
          {options.map((option) => (
            <option key={option} value={option}>
              {option}
            </option>
          ))}
        </select>

        <ChevronDown
          size={17}
          aria-hidden="true"
          style={{
            position: 'absolute',
            right: '0.9rem',
            top: '50%',
            transform: 'translateY(-50%)',
            pointerEvents: 'none',
            color: 'var(--content-tertiary)',
          }}
        />
      </div>
    </div>
  );
}

function TextArea({
  label,
  required,
  value,
  onChange,
  placeholder,
}: {
  label: string;
  required?: boolean;
  value: string;
  onChange: (value: string) => void;
  placeholder?: string;
}) {
  return (
    <div>
      <FieldLabel required={required}>{label}</FieldLabel>
      <textarea
        value={value}
        onChange={(event) => onChange(event.target.value)}
        placeholder={placeholder}
        required={required}
        maxLength={5000}
        rows={5}
        style={
          {
            ...inputStyle,
            height: 112,
            minHeight: 112,
            maxHeight: 320,
            padding: '0.75rem 0.85rem',
            lineHeight: 1.55,
            resize: 'vertical',
            overflowY: 'auto',
            fieldSizing: 'fixed',
          } as CSSProperties
        }
      />
      <div
        style={{
          display: 'flex',
          justifyContent: 'flex-end',
          marginTop: 3,
          color: 'var(--content-tertiary)',
          fontSize: '0.68rem',
        }}
      >
        {value.length}/5000
      </div>
    </div>
  );
}

function IconCircle({ children }: { children: ReactNode }) {
  return (
    <div
      style={{
        width: 44,
        height: 44,
        borderRadius: '50%',
        display: 'flex',
        alignItems: 'center',
        justifyContent: 'center',
        background: 'var(--surface-sunken)',
        color: 'var(--content-accent)',
        flexShrink: 0,
      }}
    >
      {children}
    </div>
  );
}

function SupportCard({
  title,
  body,
  icon: Icon,
}: {
  title: string;
  body: string;
  icon: LucideIcon;
}) {
  return (
    <motion.div
      whileHover={{ y: -4 }}
      transition={{ duration: 0.2 }}
      style={{
        minHeight: 174,
        padding: '1.25rem',
        border: '1px solid var(--border-subtle)',
        borderRadius: 'var(--radius-xs)',
        background: 'var(--surface-default)',
        boxShadow: 'var(--elevation-01)',
        boxSizing: 'border-box',
      }}
    >
      <IconCircle>
        <Icon size={26} strokeWidth={1.7} />
      </IconCircle>

      <div
        style={{
          width: 20,
          height: 2,
          background: 'var(--brand-accent)',
          margin: '0.7rem 0',
        }}
      />

      <h3
        style={{
          margin: 0,
          color: 'var(--content-primary)',
          fontSize: '1rem',
          fontWeight: 700,
        }}
      >
        {title}
      </h3>

      <p
        style={{
          margin: '0.5rem 0 0',
          color: 'var(--content-secondary)',
          fontSize: '0.90rem',
          lineHeight: 1.65,
        }}
      >
        {body}
      </p>
    </motion.div>
  );
}

function SideResource({
  title,
  body,
  href,
  icon: Icon,
}: {
  title: string;
  body: string;
  href: string;
  icon: LucideIcon;
}) {
  return (
    <Link
      href={href}
      style={{
        display: 'grid',
        gridTemplateColumns: '26px minmax(0,1fr) auto',
        alignItems: 'start',
        gap: '0.7rem',
        color: 'inherit',
        textDecoration: 'none',
        padding: '0.55rem 0',
      }}
    >
      <Icon size={22} color="var(--content-accent)" strokeWidth={1.8} />

      <span>
        <strong
          style={{
            display: 'block',
            color: 'var(--content-primary)',
            fontSize: '0.78rem',
            lineHeight: 1.35,
          }}
        >
          {title}
        </strong>
        <span
          style={{
            display: 'block',
            marginTop: 2,
            color: 'var(--content-secondary)',
            fontSize: '0.68rem',
            lineHeight: 1.45,
          }}
        >
          {body}
        </span>
      </span>

      <ArrowRight
        size={15}
        color="var(--content-accent)"
        style={{ marginTop: 3 }}
        aria-hidden="true"
      />
    </Link>
  );
}

export default function CustomerSupportPage() {
  const [form, setForm] = useState<FormState>(INITIAL_FORM);
  const [documents, setDocuments] = useState<UploadedDocument[]>([]);
  const [uploadingDocuments, setUploadingDocuments] = useState(false);
  const [isDraggingFiles, setIsDraggingFiles] = useState(false);
  const [submitting, setSubmitting] = useState(false);
  const [status, setStatus] = useState<'idle' | 'success' | 'error'>('idle');
  const [statusMessage, setStatusMessage] = useState('');
  const [ticketId, setTicketId] = useState('');

  const update = <K extends keyof FormState>(key: K, value: FormState[K]) => {
    setForm((current) => ({
      ...current,
      [key]: value,
    }));
  };

  const canSubmit = useMemo(
    () =>
      Boolean(
        form.fullName.trim() &&
        form.company.trim() &&
        form.workEmail.trim() &&
        form.supportArea &&
        form.supportPriority &&
        form.issue.trim() &&
        form.privacyConsent,
      ),
    [form],
  );

  const uploadDocuments = async (files: File[]) => {
    if (!files.length) return;

    const availableSlots = MAX_FILES - documents.length;

    if (availableSlots <= 0) {
      setStatus('error');
      setStatusMessage(`You can upload a maximum of ${MAX_FILES} files.`);
      return;
    }

    const selectedFiles = files.slice(0, availableSlots);

    const invalidFile = selectedFiles.find((file) => {
      const extension = file.name.split('.').pop()?.toLowerCase() || '';
      return !ALLOWED_FILE_EXTENSIONS.has(extension) || file.size <= 0 || file.size > MAX_FILE_SIZE;
    });

    if (invalidFile) {
      const extension = invalidFile.name.split('.').pop()?.toLowerCase() || '';

      setStatus('error');

      if (!ALLOWED_FILE_EXTENSIONS.has(extension)) {
        setStatusMessage(
          `"${invalidFile.name}" is not an accepted file type. Use PDF, DOC, DOCX, XLS, XLSX, TXT, PNG, JPG, JPEG or ZIP.`,
        );
      } else if (invalidFile.size <= 0) {
        setStatusMessage(`"${invalidFile.name}" is empty and cannot be uploaded.`);
      } else {
        setStatusMessage(`"${invalidFile.name}" exceeds the 2 MB file size limit.`);
      }

      return;
    }

    setStatus('idle');
    setStatusMessage('');
    setUploadingDocuments(true);

    try {
      const uploaded: UploadedDocument[] = [];

      for (const file of selectedFiles) {
        const extension = file.name.split('.').pop()?.toLowerCase() || '';
        const contentType = CONTENT_TYPE_BY_EXTENSION[extension] || 'application/octet-stream';

        const authorizationResponse = await fetch('/api/customer-support-documents/upload', {
          method: 'POST',
          headers: {
            'Content-Type': 'application/json',
            Accept: 'application/json',
          },
          body: JSON.stringify({
            fileName: file.name,
            contentType,
            fileSize: file.size,
          }),
          cache: 'no-store',
        });

        const responseContentType = authorizationResponse.headers.get('content-type') || '';

        const authorizationResult: {
          success?: boolean;
          message?: string;
          presignedUrl?: string;
          pathname?: string;
          contentType?: string;
        } = responseContentType.includes('application/json')
          ? await authorizationResponse.json().catch(() => ({}))
          : {
              success: false,
              message: await authorizationResponse.text().catch(() => ''),
            };

        if (
          !authorizationResponse.ok ||
          !authorizationResult.success ||
          !authorizationResult.presignedUrl ||
          !authorizationResult.pathname
        ) {
          throw new Error(
            authorizationResult.message || 'Unable to authorize the document upload.',
          );
        }

        const signedContentType = authorizationResult.contentType || contentType;

        const blobResponse = await fetch(authorizationResult.presignedUrl, {
          method: 'PUT',
          headers: {
            'Content-Type': signedContentType,
          },
          body: file,
        });

        if (!blobResponse.ok) {
          const blobError = await blobResponse.text().catch(() => '');

          throw new Error(
            blobError
              ? `Unable to upload "${file.name}" to secure storage. ${blobError}`
              : `Unable to upload "${file.name}" to secure storage.`,
          );
        }

        uploaded.push({
          id: `${file.name}-${file.size}-${file.lastModified}-${Date.now()}-${uploaded.length}`,
          fileName: file.name,
          blobPathname: authorizationResult.pathname,
          contentType: signedContentType,
          fileSize: file.size,
        });
      }

      setDocuments((current) => [...current, ...uploaded]);
    } catch (error) {
      console.error('[TRYVION Customer Support Document Upload]', error);
      setStatus('error');
      setStatusMessage(
        error instanceof Error ? error.message : 'Unable to upload the document. Please try again.',
      );
    } finally {
      setUploadingDocuments(false);
    }
  };

  const handleDocuments = async (event: ChangeEvent<HTMLInputElement>) => {
    const files = Array.from(event.target.files ?? []);
    event.target.value = '';
    await uploadDocuments(files);
  };

  const handleDocumentDrop = async (event: DragEvent<HTMLLabelElement>) => {
    event.preventDefault();
    event.stopPropagation();
    setIsDraggingFiles(false);

    if (uploadingDocuments || submitting) return;

    const files = Array.from(event.dataTransfer.files ?? []);
    await uploadDocuments(files);
  };

  const removeDocument = (id: string) => {
    setDocuments((current) => current.filter((document) => document.id !== id));
  };

  const handleSubmit = async (event?: FormEvent<HTMLFormElement>) => {
    event?.preventDefault();

    if (submitting || uploadingDocuments) return;

    setStatus('idle');
    setStatusMessage('');

    if (!form.privacyConsent) {
      setStatus('error');
      setStatusMessage('Please agree to the Privacy Policy before submitting.');
      return;
    }

    if (!canSubmit) {
      setStatus('error');
      setStatusMessage('Please complete all required fields before submitting.');
      return;
    }

    if (documents.some((document) => !document.blobPathname)) {
      setStatus('error');
      setStatusMessage(
        'One or more attachments are not securely uploaded. Please remove and upload them again.',
      );
      return;
    }

    setSubmitting(true);

    try {
      const response = await fetch('/api/customer-support/submit', {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json',
          Accept: 'application/json',
        },
        body: JSON.stringify({
          fullName: form.fullName.trim(),
          company: form.company.trim(),
          workEmail: form.workEmail.trim().toLowerCase(),
          phone: form.phone.trim(),
          supportArea: form.supportArea,
          supportPriority: form.supportPriority,
          customerProjectReference: form.customerProjectReference.trim(),
          issue: form.issue.trim(),
          privacyConsent: form.privacyConsent,
          marketingConsent: form.marketingConsent,
          website: form.website.trim(),
          attachments: documents.map((document) => ({
            fileName: document.fileName,
            blobPathname: document.blobPathname,
            contentType: document.contentType,
            fileSize: document.fileSize,
          })),
        }),
        cache: 'no-store',
      });

      const responseContentType = response.headers.get('content-type') || '';

      const result: {
        success?: boolean;
        message?: string;
        ticketId?: string;
      } = responseContentType.includes('application/json')
        ? await response.json().catch(() => ({}))
        : {
            success: false,
            message: await response.text().catch(() => ''),
          };

      if (!response.ok || result.success !== true) {
        throw new Error(
          result.message ||
            `Unable to submit your support request. Server returned ${response.status}.`,
        );
      }

      setTicketId(result.ticketId || '');
      setStatus('success');
      setStatusMessage(
        result.message ||
          'Your support request has been received. Our team will contact you shortly.',
      );
      setForm(INITIAL_FORM);
      setDocuments([]);

      window.scrollTo({
        top: 0,
        behavior: 'smooth',
      });
    } catch (error) {
      console.error('[TRYVION Customer Support Submission]', error);
      setStatus('error');
      setStatusMessage(
        error instanceof Error
          ? error.message
          : 'Unable to connect to TRYVION. Please try again shortly.',
      );
    } finally {
      setSubmitting(false);
    }
  };

  return (
    <>
      <style>{responsiveStyles}</style>

      <main className="cs-page">
        <section className="cs-hero" aria-labelledby="customer-support-title">
          <div className="cs-hero-image" aria-hidden="true" />
          <div className="cs-hero-overlay" aria-hidden="true" />

          <div className="cs-container cs-hero-inner">
            <nav className="cs-breadcrumbs" aria-label="Breadcrumb">
              <Link href="/">Home</Link>
              <span aria-hidden="true">›</span>
              <Link href="/contact">Contact</Link>
              <span aria-hidden="true">›</span>
              <span aria-current="page">Customer Support</span>
            </nav>

            <motion.div
              className="cs-hero-copy"
              initial={{ opacity: 0, y: 22 }}
              animate={{ opacity: 1, y: 0 }}
              transition={{ duration: 0.65, ease: 'easeOut' }}
            >
              <div className="cs-eyebrow">
                <span />
                CUSTOMER SUPPORT
              </div>

              <h1 id="customer-support-title">
                We’re here to
                <br />
                keep you moving forward.
              </h1>

              <p>
                Get assistance with an existing TRYVION engagement, service or supported
                environment.
              </p>
            </motion.div>

            <div className="cs-hero-points" style={{ maxWidth: 900 }}>
              {HERO_POINTS.map(({ title, body, icon: Icon }, index) => (
                <motion.div
                  className="cs-hero-point"
                  key={title}
                  initial={{ opacity: 0, y: 16 }}
                  animate={{ opacity: 1, y: 0 }}
                  transition={{ duration: 0.45, delay: 0.12 + index * 0.07 }}
                >
                  <div className="cs-hero-icon">
                    <Icon size={26} strokeWidth={1.65} />
                  </div>

                  <div>
                    <strong>{title}</strong>
                    <span>{body}</span>
                  </div>
                </motion.div>
              ))}
            </div>
          </div>
        </section>

        <section className="cs-help-section">
          <div className="cs-container">
            <div className="cs-section-heading">
              <span className="cs-gold-line" />
              <h2>How can we help?</h2>
              <p>
                Tell us the area you need help with and we’ll connect you with the right support
                team.
              </p>
            </div>

            <div className="cs-help-grid">
              {HELP_ITEMS.map((item) => (
                <SupportCard
                  key={item.title}
                  title={item.title}
                  body={item.body}
                  icon={item.icon}
                />
              ))}
            </div>
          </div>
        </section>

        <section className="cs-form-section" id="support-request">
          <div className="cs-container">
            <div className="cs-form-heading">
              <h2>Submit a support request</h2>
              <p>Please provide the details below and our team will get back to you.</p>
            </div>

            <form onSubmit={handleSubmit} noValidate>
              <div className="cs-form-layout">
                <div className="cs-form-card">
                  <div className="cs-form-grid">
                    <TextInput
                      label="Full Name"
                      required
                      value={form.fullName}
                      onChange={(value) => update('fullName', value)}
                      placeholder="Enter your full name"
                    />

                    <TextInput
                      label="Company"
                      required
                      value={form.company}
                      onChange={(value) => update('company', value)}
                      placeholder="Enter your company name"
                    />

                    <TextInput
                      label="Work Email"
                      required
                      type="email"
                      value={form.workEmail}
                      onChange={(value) => update('workEmail', value)}
                      placeholder="name@company.com"
                    />

                    <TextInput
                      label="Phone (Optional)"
                      type="tel"
                      value={form.phone}
                      onChange={(value) => update('phone', value)}
                      placeholder="+1 (555) 000-0000"
                    />

                    <SelectInput
                      label="Support Area"
                      required
                      value={form.supportArea}
                      onChange={(value) => update('supportArea', value)}
                      options={SUPPORT_AREAS}
                      placeholder="Select support area"
                    />

                    <div className="cs-priority-field">
                      <SelectInput
                        label="Support Priority"
                        required
                        value={form.supportPriority}
                        onChange={(value) => update('supportPriority', value)}
                        options={SUPPORT_PRIORITIES}
                        placeholder="Select priority"
                      />
                      <span
                        className="cs-priority-info"
                        title="Choose the priority based on the business impact of the issue."
                        aria-label="Support priority information"
                      >
                        <Info size={13} />
                      </span>
                    </div>

                    <div className="cs-reference-field">
                      <TextInput
                        label="Customer / Project Reference (Optional)"
                        value={form.customerProjectReference}
                        onChange={(value) => update('customerProjectReference', value)}
                        placeholder="Enter reference number, project ID, contract ID, etc."
                      />
                    </div>

                    <div className="cs-issue-field">
                      <TextArea
                        label="Tell us about the issue"
                        required
                        value={form.issue}
                        onChange={(value) => update('issue', value)}
                        placeholder="Please describe the issue or assistance you need."
                      />
                    </div>
                  </div>

                  <div className="cs-upload-block">
                    <FieldLabel>Attach files (Optional)</FieldLabel>

                    <label
                      className={`cs-dropzone ${isDraggingFiles ? 'is-dragging' : ''}`}
                      onDragEnter={(event) => {
                        event.preventDefault();
                        event.stopPropagation();
                        if (!uploadingDocuments && !submitting) setIsDraggingFiles(true);
                      }}
                      onDragOver={(event) => {
                        event.preventDefault();
                        event.stopPropagation();
                        event.dataTransfer.dropEffect = 'copy';
                      }}
                      onDragLeave={(event) => {
                        event.preventDefault();
                        event.stopPropagation();
                        if (event.currentTarget === event.target) setIsDraggingFiles(false);
                      }}
                      onDrop={(event) => {
                        void handleDocumentDrop(event);
                      }}
                      aria-busy={uploadingDocuments}
                    >
                      <Upload size={21} />
                      <span>
                        <strong>Drag and drop files here or browse</strong>
                        <small>
                          Max file size 2MB. Supported formats: PDF, DOC, DOCX, XLS, XLSX, TXT, PNG,
                          JPG, JPEG, ZIP
                        </small>
                      </span>

                      <input
                        type="file"
                        multiple
                        disabled={uploadingDocuments || submitting}
                        onChange={handleDocuments}
                        accept=".pdf,.doc,.docx,.xls,.xlsx,.txt,.png,.jpg,.jpeg,.zip"
                      />
                    </label>

                    {documents.length > 0 && (
                      <div className="cs-file-list">
                        {documents.map((document) => (
                          <div className="cs-file-row" key={document.id}>
                            <Paperclip size={16} />

                            <div>
                              <strong>{document.fileName}</strong>
                              <span>{(document.fileSize / 1024 / 1024).toFixed(2)} MB</span>
                            </div>

                            <button
                              type="button"
                              onClick={() => removeDocument(document.id)}
                              disabled={uploadingDocuments || submitting}
                            >
                              Remove
                            </button>
                          </div>
                        ))}
                      </div>
                    )}
                  </div>

                  <div className="cs-consent">
                    <label>
                      <input
                        type="checkbox"
                        checked={form.privacyConsent}
                        onChange={(event) => update('privacyConsent', event.target.checked)}
                      />
                      <span>
                        I agree to the processing of my personal data in accordance with the{' '}
                        <Link href="/privacy">Privacy Policy</Link>.<em>*</em>
                      </span>
                    </label>

                    <label>
                      <input
                        type="checkbox"
                        checked={form.marketingConsent}
                        onChange={(event) => update('marketingConsent', event.target.checked)}
                      />
                      <span>
                        I would like to receive insights, updates, and promotional communications
                        from TRYVION.
                      </span>
                    </label>
                  </div>

                  {form.website && (
                    <input
                      type="text"
                      value={form.website}
                      onChange={(event) => update('website', event.target.value)}
                      tabIndex={-1}
                      autoComplete="off"
                      aria-hidden="true"
                      className="cs-honeypot"
                    />
                  )}

                  <button
                    type="button"
                    onClick={() => {
                      void handleSubmit();
                    }}
                    disabled={!canSubmit || submitting || uploadingDocuments}
                    className="cs-submit-button"
                  >
                    {uploadingDocuments
                      ? 'Uploading…'
                      : submitting
                        ? 'Submitting…'
                        : 'Submit Request'}
                    {!submitting && !uploadingDocuments && <ArrowRight size={16} />}
                  </button>

                  {status === 'error' && (
                    <div className="cs-status cs-status-error" role="alert">
                      {statusMessage}
                    </div>
                  )}

                  {status === 'success' && (
                    <div className="cs-status cs-status-success" role="status">
                      <Check size={18} />
                      <div>
                        <strong>{statusMessage}</strong>
                        {ticketId && <span>Support Ticket: {ticketId}</span>}
                      </div>
                    </div>
                  )}
                </div>

                <aside className="cs-sidebar">
                  <div className="cs-resource-card">
                    <h3>Before you submit</h3>
                    <p>Check out our support resources — you might find a quick answer.</p>

                    <div className="cs-resource-list">
                      <SideResource
                        title="Knowledge Base"
                        body="Browse articles and user guides"
                        href="#knowledge-base"
                        icon={FileText}
                      />
                      <SideResource
                        title="System Status"
                        body="Check live status of our services"
                        href="#system-status"
                        icon={Globe2}
                      />
                      <SideResource
                        title="Support Process"
                        body="Learn how our support works"
                        href="#support-process"
                        icon={ShieldCheck}
                      />
                      <SideResource
                        title="FAQs"
                        body="Find answers to common questions"
                        href="#faqs"
                        icon={HelpCircle}
                      />
                    </div>
                  </div>

                  <div className="cs-urgent-card">
                    <div className="cs-urgent-icon">
                      <Info size={20} />
                    </div>

                    <div>
                      <h3>For urgent issues</h3>
                      <p>
                        If you are experiencing a critical issue impacting your business operations,
                        please call our priority support line.
                      </p>

                      <strong>Priority Support</strong>

                      <a href="tel:+44(0) 79517 85497">
                        <Phone size={20} />
                        +44(0) 79517 85497
                      </a>

                      <span>Available 24/7 for critical issues</span>
                    </div>
                  </div>
                </aside>
              </div>
            </form>
          </div>
        </section>

        <section className="cs-cta">
          <div className="cs-container cs-cta-inner">
            <div className="cs-cta-icon">
              <Headphones size={30} />
            </div>

            <div>
              <h2>Need to talk to a support expert?</h2>
              <p>If you prefer to speak with someone directly, our team is here to help.</p>
            </div>

            <a className="cs-cta-button" href="tel:+44(0) 79517 85497">
              Call Support
              <ArrowRight size={18} />
            </a>
          </div>
        </section>

        <section className="cs-trust">
          <div className="cs-container cs-trust-grid">
            {TRUST_ITEMS.map(({ title, body, icon: Icon }) => (
              <div className="cs-trust-item" key={title}>
                <Icon size={34} strokeWidth={1.55} />
                <div>
                  <strong>{title}</strong>
                  <span>{body}</span>
                </div>
              </div>
            ))}
          </div>
        </section>

        <div id="knowledge-base" className="cs-anchor" aria-hidden="true" />
        <div id="system-status" className="cs-anchor" aria-hidden="true" />
        <div id="support-process" className="cs-anchor" aria-hidden="true" />
        <div id="faqs" className="cs-anchor" aria-hidden="true" />
      </main>
    </>
  );
}

const responsiveStyles = `
  .cs-page {
    background: var(--surface-default);
    color: var(--content-primary);
    font-family: var(--family-text);
  }

  .cs-container {
    width: min(var(--layout-content-wide), calc(100% - 2.5rem));
    margin: 1.5rem auto;
  }

  .cs-hero {
    position: relative;
    min-height: 500px;
    overflow: hidden;
    background: #071c35;
    color: #fff;
  }

  .cs-hero-image,
  .cs-hero-overlay {
    position: absolute;
    inset: 0;
  }

  .cs-hero-image {
    background-image: url("${HERO_IMAGE}");
    background-size: cover;
    background-position: center right;
  }

  .cs-hero-overlay {
    background:
      linear-gradient(
        90deg,
        rgba(4, 25, 48, 0.98) 0%,
        rgba(4, 25, 48, 0.95) 35%,
        rgba(4, 25, 48, 0.58) 60%,
        rgba(4, 25, 48, 0.15) 100%
      );
  }

  .cs-hero-inner {
    position: relative;
    z-index: 1;
    min-height: 500px;
    padding: clamp(7.5rem, 11vw, 9.5rem) 0 3rem;
    box-sizing: border-box;
  }

  .cs-breadcrumbs {
    display: flex;
    align-items: center;
    gap: 0.5rem;
    margin-bottom: 2rem;
    color: rgba(255,255,255,0.82);
    font-size: 0.75rem;
  }

  .cs-breadcrumbs a {
    color: #fff;
    text-decoration: none;
  }

  .cs-hero-copy {
    max-width: 650px;
  }

  .cs-eyebrow {
    display: inline-flex;
    align-items: center;
    gap: 0.65rem;
    margin-bottom: 1rem;
    color: #c9a24b;
    font-size: 0.72rem;
    font-weight: 800;
    letter-spacing: 0.09em;
  }

  .cs-eyebrow span {
    width: 23px;
    height: 2px;
    background: #c9a24b;
  }

  .cs-hero h1 {
    margin: 0;
    color: #fff;
    font-family: var(--family-display);
    font-size: clamp(2.35rem, 5vw, 4.25rem);
    line-height: 1.05;
    letter-spacing: -0.045em;
    font-weight: 700;
  }

  .cs-hero-copy p {
    max-width: 590px;
    margin: 1rem 0 0;
    color: rgba(255,255,255,0.8);
    font-size: 1.10rem;
    line-height: 1.7;
  }

  .cs-hero-points {
    display: grid;
    grid-template-columns: repeat(3, minmax(0, 1fr));
    gap: 1rem;
    max-width: 900px;
    margin-top: 2.25rem;
    margin-bottom: 2.25rem;
  }

  .cs-hero-point {
    display: flex;
    align-items: flex-start;
    gap: 0.75rem;
    padding-left: 0.8rem;
    border-left: 1px solid rgba(255,255,255,0.2);
  }

  .cs-hero-icon {
    width: 48px;
    height: 48px;
    display: flex;
    align-items: center;
    justify-content: center;
    border: 1px solid rgba(201,162,75,0.8);
    border-radius: 50%;
    color: #c9a24b;
    flex-shrink: 0;
  }

  .cs-hero-point strong,
  .cs-hero-point span {
    display: block;
  }

  .cs-hero-point strong {
    margin-top: 0.15rem;
    color: rgba(255,255,255,0.92);
    font-size: 1rem;
    line-height: 1.35;
  }

  .cs-hero-point span {
    margin-top: 0.35rem;
    color: rgba(255,255,255,0.68);
    font-size: 0.85rem;
    line-height: 1.5;
  }

  .cs-help-section {
    padding: clamp(3.5rem, 7vw, 5.5rem) 0;
    background: var(--surface-default);
  }

  .cs-section-heading {
    margin-bottom: 2.4rem;
    text-align: center;
  }

  .cs-gold-line {
    display: block;
    width: 24px;
    height: 2px;
    margin: 0 auto 0.85rem;
    background: var(--brand-accent);
  }

  .cs-section-heading h2,
  .cs-form-heading h2,
  .cs-cta h2 {
    margin: 0;
    color: var(--content-primary);
    font-family: var(--family-display);
    letter-spacing: -0.025em;
  }

  .cs-section-heading h2 {
    font-size: clamp(1.6rem, 3vw, 2.2rem);
  }

  .cs-section-heading p {
    max-width: 700px;
    margin: 0.65rem auto 0;
    color: var(--content-secondary);
    font-size: 1rem;
    line-height: 1.6;
  }

  .cs-help-grid {
    display: grid;
    grid-template-columns: repeat(5, minmax(0, 1fr));
    gap: 1rem;
  }

  .cs-form-section {
    padding: clamp(3.5rem, 7vw, 5rem) 0;
    background: var(--surface-sunken);
  }

  .cs-form-heading {
    margin-bottom: 2rem;
    text-align: center;
  }

  .cs-form-heading h2 {
    font-size: clamp(1.55rem, 3vw, 2.15rem);
  }

  .cs-form-heading p {
    margin: 0.5rem 0 0;
    color: var(--content-secondary);
    font-size: 1rem;
  }

  .cs-form-layout {
    display: grid;
    grid-template-columns: minmax(0, 1fr) 285px;
    gap: 1.5rem;
    align-items: start;
  }

  .cs-form-card {
    padding: clamp(1.25rem, 3vw, 2rem);
    border: 1px solid var(--border-subtle);
    border-radius: var(--radius-xs);
    background: var(--surface-default);
    box-shadow: var(--elevation-01);
  }

  .cs-form-grid {
    display: grid;
    grid-template-columns: repeat(2, minmax(0, 1fr));
    gap: 1rem 1.15rem;
  }

  .cs-reference-field,
  .cs-issue-field {
    grid-column: 1 / -1;
  }

  .cs-priority-field {
    position: relative;
  }

  .cs-priority-info {
    position: absolute;
    left: 7.9rem;
    top: 1px;
    display: inline-flex;
    color: var(--content-tertiary);
  }

  .cs-upload-block {
    margin-top: 1rem;
  }

  .cs-dropzone {
    min-height: 76px;
    display: flex;
    align-items: center;
    justify-content: center;
    gap: 0.8rem;
    padding: 0.85rem 1rem;
    border: 1px dashed var(--border-default);
    border-radius: var(--radius-xs);
    background: var(--surface-sunken);
    color: var(--content-accent);
    text-align: center;
    cursor: pointer;
    box-sizing: border-box;
  }

  .cs-dropzone span {
    display: block;
  }

  .cs-dropzone strong,
  .cs-dropzone small {
    display: block;
  }

  .cs-dropzone strong {
    color: var(--content-primary);
    font-size: 0.72rem;
  }

  .cs-dropzone small {
    margin-top: 0.25rem;
    color: var(--content-tertiary);
    font-size: 0.63rem;
    line-height: 1.45;
  }

  .cs-dropzone:hover,
  .cs-dropzone.is-dragging {
    border-color: var(--content-accent);
    background: var(--surface-sunken);
  }

  .cs-dropzone.is-dragging {
    box-shadow: 0 0 0 2px rgba(201,162,75,0.14);
  }

  .cs-dropzone input {
    display: none;
  }

  .cs-file-list {
    display: grid;
    gap: 0.45rem;
    margin-top: 0.65rem;
  }

  .cs-file-row {
    display: grid;
    grid-template-columns: 18px minmax(0,1fr) auto;
    align-items: center;
    gap: 0.65rem;
    padding: 0.6rem 0.7rem;
    border: 1px solid var(--border-subtle);
    border-radius: var(--radius-xs);
    background: var(--surface-default);
  }

  .cs-file-row > svg {
    color: var(--content-accent);
  }

  .cs-file-row strong,
  .cs-file-row span {
    display: block;
  }

  .cs-file-row strong {
    overflow: hidden;
    text-overflow: ellipsis;
    white-space: nowrap;
    color: var(--content-primary);
    font-size: 0.72rem;
  }

  .cs-file-row span {
    margin-top: 2px;
    color: var(--content-tertiary);
    font-size: 0.62rem;
  }

  .cs-file-row button {
    border: 0;
    background: transparent;
    color: var(--content-tertiary);
    font: inherit;
    font-size: 0.66rem;
    font-weight: 700;
    cursor: pointer;
  }

  .cs-consent {
    display: grid;
    gap: 0.55rem;
    margin-top: 1.1rem;
  }

  .cs-consent label {
    display: flex;
    align-items: flex-start;
    gap: 0.55rem;
    color: var(--content-secondary);
    font-size: 0.68rem;
    line-height: 1.55;
    cursor: pointer;
  }

  .cs-consent input {
    width: 15px;
    height: 15px;
    margin-top: 1px;
    flex-shrink: 0;
    accent-color: var(--brand-accent);
  }

  .cs-consent a {
    color: var(--content-accent);
    font-weight: 700;
  }

  .cs-consent em {
    margin-left: 2px;
    color: var(--content-accent);
    font-style: normal;
    font-weight: 700;
  }

  .cs-submit-button {
    min-height: 46px;
    display: inline-flex;
    align-items: center;
    gap: 0.55rem;
    margin-top: 1.15rem;
    padding: 0 1.2rem;
    border: 0;
    border-radius: var(--radius-xs);
    background: var(--action-primary-default);
    color: var(--action-primary-on-action);
    font-family: var(--family-text);
    font-size: 0.76rem;
    font-weight: 700;
    cursor: pointer;
  }

  .cs-submit-button:disabled {
    opacity: 0.55;
    cursor: not-allowed;
  }

  .cs-status {
    display: flex;
    align-items: flex-start;
    gap: 0.55rem;
    margin-top: 0.85rem;
    padding: 0.75rem 0.85rem;
    border: 1px solid var(--border-subtle);
    border-radius: var(--radius-xs);
    font-size: 0.7rem;
    line-height: 1.5;
  }

  .cs-status-error {
    color: var(--content-primary);
    background: var(--surface-sunken);
  }

  .cs-status-success {
    color: var(--content-primary);
    background: var(--surface-sunken);
  }

  .cs-status-success svg {
    color: var(--content-accent);
    flex-shrink: 0;
  }

  .cs-status strong,
  .cs-status span {
    display: block;
  }

  .cs-status span {
    margin-top: 3px;
    color: var(--content-secondary);
  }

  .cs-sidebar {
    display: grid;
    gap: 0.9rem;
  }

  .cs-resource-card {
    padding: 1.25rem;
    border-radius: var(--radius-xs);
    background: #eef4ff;
    border: 1px solid rgba(11, 30, 61, 0.05);
  }

  /* Theme-only override: preserve the existing light design,
     while allowing the global TRYVION theme to render this
     resource card correctly in dark mode. */
  [data-theme="dark"] .cs-resource-card {
    background: var(--surface-raised);
    border-color: var(--border-subtle);
  }

  .cs-resource-card h3,
  .cs-urgent-card h3 {
    margin: 0;
    color: var(--content-primary);
    font-family: var(--family-display);
    font-size: 1rem;
  }

  .cs-resource-card > p,
  .cs-urgent-card p {
    margin: 0.45rem 0 0;
    color: var(--content-secondary);
    font-size: 0.75rem;
    line-height: 1.55;
  }

  .cs-resource-list {
    display: grid;
    gap: 0.25rem;
    margin-top: 1rem;
    font-size: 0.75rem;
  }

  .cs-urgent-card {
    display: grid;
    grid-template-columns: 28px minmax(0,1fr);
    gap: 0.65rem;
    padding: 1.25rem;
    border: 1px solid var(--border-subtle);
    border-radius: var(--radius-xs);
    background: var(--surface-default);
  }

  .cs-urgent-icon {
    width: 28px;
    height: 28px;
    display: flex;
    align-items: center;
    justify-content: center;
    border: 1px solid #ef4444;
    border-radius: 50%;
    color: #ef4444;
  }

  .cs-urgent-card strong {
    display: block;
    margin-top: 0.9rem;
    color: var(--content-primary);
    font-size: 0.95rem;
  }

  .cs-urgent-card a {
    display: flex;
    align-items: center;
    gap: 0.4rem;
    margin-top: 0.4rem;
    color: var(--content-primary);
    font-size: 1rem;
    font-weight: 800;
    text-decoration: none;
  }

  .cs-urgent-card a svg {
    color: var(--content-accent);
  }

  .cs-urgent-card span {
    display: block;
    margin-top: 0.35rem;
    color: var(--content-secondary);
    font-size: 0.80rem;
  }

  .cs-cta {
    background: #031a33;
    color: #fff;
    padding: 1rem 0;
  }

  .cs-cta-inner {
    display: grid;
    grid-template-columns: 60px minmax(0,1fr) 180px;
    align-items: center;
    gap: 1rem;
    min-height: 95px;
    margin-top: 1.5rem;
    margin-bottom: 1.5rem;
  }

  .cs-cta-icon {
    width: 56px;
    height: 56px;
    display: flex;
    align-items: center;
    justify-content: center;
    border: 1px solid #c9a24b;
    border-radius: 50%;
    color: #c9a24b;
  }

  .cs-cta h2 {
    color: #fff;
    font-size: 1.25rem;
  }

  .cs-cta p {
    margin: 0.25rem 0 0;
    color: rgba(255,255,255,0.68);
    font-size: 0.95rem;
  }

  .cs-cta-button {
    min-height: 40px;
    display: inline-flex;
    align-items: center;
    justify-content: center;
    gap: 0.9rem;
    border: 1px solid #c9a24b;
    border-radius: var(--radius-xs);
    color: #c9a24b;
    text-decoration: none;
    font-size: 0.95rem;
    font-weight: 700;
  }

  .cs-trust {
    padding: 1.6rem 0;
    background: var(--surface-default);
  }

  .cs-trust-grid {
    display: grid;
    grid-template-columns: repeat(4, minmax(0,1fr));
  }

  .cs-trust-item {
    display: flex;
    align-items: flex-start;
    gap: 0.75rem;
    padding: 0 1rem;
    border-right: 1px solid var(--border-subtle);
  }

  .cs-trust-item:first-child {
    padding-left: 0;
  }

  .cs-trust-item:last-child {
    padding-right: 0;
    border-right: 0;
  }

  .cs-trust-item > svg {
    color: var(--content-primary);
    flex-shrink: 0;
  }

  .cs-trust-item strong,
  .cs-trust-item span {
    display: block;
  }

  .cs-trust-item strong {
    color: var(--content-primary);
    font-size: 1.10rem;
  }

  .cs-trust-item span {
    margin-top: 0.25rem;
    color: var(--content-tertiary);
    font-size: 0.90rem;
    line-height: 1.45;
  }

  .cs-honeypot {
    position: absolute !important;
    left: -10000px !important;
    width: 1px !important;
    height: 1px !important;
    opacity: 0 !important;
    pointer-events: none !important;
  }

  .cs-anchor {
    scroll-margin-top: 100px;
  }

  @media (max-width: 1000px) {
    .cs-help-grid {
      grid-template-columns: repeat(2, minmax(0,1fr));
    }

    .cs-form-layout {
      grid-template-columns: 1fr;
    }

    .cs-sidebar {
      grid-template-columns: repeat(2, minmax(0,1fr));
    }
  }

  @media (max-width: 760px) {
    .cs-container {
      width: min(100% - 2rem, var(--layout-content-wide));
    }

    .cs-hero {
      min-height: 620px;
    }

    .cs-hero-inner {
      min-height: 620px;
      padding-top: 7rem;
    }

    .cs-hero-image {
      background-position: 72% center;
    }

    .cs-hero-overlay {
      background:
        linear-gradient(
          180deg,
          rgba(4,25,48,0.98) 0%,
          rgba(4,25,48,0.94) 55%,
          rgba(4,25,48,0.78) 100%
        );
    }

    .cs-hero-points {
      grid-template-columns: 1fr;
      gap: 0.7rem;
    }

    .cs-hero-point {
      max-width: 360px;
    }

    .cs-form-grid {
      grid-template-columns: 1fr;
    }

    .cs-reference-field,
    .cs-issue-field {
      grid-column: auto;
    }

    .cs-sidebar {
      grid-template-columns: 1fr;
    }

    .cs-cta-inner {
      grid-template-columns: 52px minmax(0,1fr);
    }

    .cs-cta-button {
      grid-column: 2;
    }

    .cs-trust-grid {
      grid-template-columns: repeat(2, minmax(0,1fr));
      gap: 1rem 0;
    }

    .cs-trust-item {
      padding: 0 0.75rem;
    }

    .cs-trust-item:nth-child(2) {
      border-right: 0;
    }

    .cs-trust-item:nth-child(3),
    .cs-trust-item:nth-child(4) {
      padding-top: 1rem;
      border-top: 1px solid var(--border-subtle);
    }
  }

  @media (max-width: 560px) {
    .cs-help-grid {
      grid-template-columns: 1fr;
    }

    .cs-trust-grid {
      grid-template-columns: 1fr;
    }

    .cs-trust-item,
    .cs-trust-item:nth-child(3),
    .cs-trust-item:nth-child(4) {
      padding: 0.85rem 0;
      border-right: 0;
      border-top: 1px solid var(--border-subtle);
    }

    .cs-trust-item:first-child {
      padding-top: 0;
      border-top: 0;
    }

    .cs-cta-inner {
      grid-template-columns: 48px minmax(0,1fr);
    }

    .cs-cta-button {
      grid-column: 1 / -1;
    }
  }
`;
