/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    insights: Insight;
    team: Team;
    'contact-submissions': ContactSubmission;
    'rfp-submissions': RfpSubmission;
    'sales-enquiries': SalesEnquiry;
    'customer-support': CustomerSupport;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    insights: InsightsSelect<false> | InsightsSelect<true>;
    team: TeamSelect<false> | TeamSelect<true>;
    'contact-submissions': ContactSubmissionsSelect<false> | ContactSubmissionsSelect<true>;
    'rfp-submissions': RfpSubmissionsSelect<false> | RfpSubmissionsSelect<true>;
    'sales-enquiries': SalesEnquiriesSelect<false> | SalesEnquiriesSelect<true>;
    'customer-support': CustomerSupportSelect<false> | CustomerSupportSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {
    'site-settings': SiteSetting;
  };
  globalsSelect: {
    'site-settings': SiteSettingsSelect<false> | SiteSettingsSelect<true>;
  };
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt: string;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "insights".
 */
export interface Insight {
  id: number;
  title: string;
  /**
   * Auto-generated from title. Editable once set.
   */
  slug: string;
  excerpt: string;
  body: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  author?: (number | null) | Team;
  category: 'Research' | 'SAP' | 'AI & Data' | 'Cloud' | 'Digital Engineering' | 'Managed Services' | 'Talent';
  /**
   * Scheduled publish date and time.
   */
  publishedAt?: string | null;
  /**
   * e.g. "8 min read"
   */
  readTime?: string | null;
  image: number | Media;
  /**
   * Leave blank to use title and excerpt as defaults.
   */
  seo?: {
    /**
     * Defaults to article title.
     */
    metaTitle?: string | null;
    /**
     * Defaults to excerpt.
     */
    metaDescription?: string | null;
    /**
     * Defaults to article image.
     */
    ogImage?: (number | null) | Media;
  };
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "team".
 */
export interface Team {
  id: number;
  name: string;
  role: string;
  bio?: string | null;
  avatar?: (number | null) | Media;
  /**
   * LinkedIn profile URL (full URL including https://)
   */
  linkedin?: string | null;
  email?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Website contact and business enquiry submissions received through TRYVION.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contact-submissions".
 */
export interface ContactSubmission {
  id: number;
  /**
   * Name provided by the website visitor.
   */
  fullName: string;
  /**
   * Company or organisation name.
   */
  company: string;
  /**
   * Business email address.
   */
  email: string;
  /**
   * Optional international telephone number.
   */
  phone?: string | null;
  /**
   * Primary TRYVION service selected by the visitor.
   */
  mainService:
    | 'Tryvion Applications'
    | 'Tryvion AI'
    | 'Tryvion Data & Analytics'
    | 'Tryvion Cloud'
    | 'Tryvion Labs'
    | 'Tryvion Talent'
    | 'Tryvion Academy'
    | 'Tryvion Operate';
  /**
   * Specific service selected under the primary service. Server-side validation enforces the valid pairing.
   */
  subService?:
    | (
        | 'SAP S/4HANA'
        | 'SAP SuccessFactors'
        | 'SAP Customer Experience (CX)'
        | 'SAP Ariba'
        | 'SAP Business Technology Platform (BTP)'
        | 'Enterprise AI Strategy'
        | 'Enterprise AI Platforms'
        | 'Intelligent Automation'
        | 'Data Engineering'
        | 'Data Platforms'
        | 'Data Integration'
        | 'Data Governance'
        | 'Business Intelligence'
        | 'Enterprise Reporting'
        | 'Advanced & Predictive Analytics'
        | 'Cloud Strategy'
        | 'Cloud Migration & Modernization'
        | 'Amazon Web Services (AWS)'
        | 'Microsoft Azure'
        | 'Google Cloud Platform (GCP)'
        | 'Custom Application Development'
        | 'API Management & Integration'
        | 'Enterprise Integration'
        | 'DevSecOps & Platform Engineering'
        | 'SAP Talent Solutions'
        | 'Technology Contract Staffing'
        | 'Permanent Hiring'
        | 'Executive Search'
        | 'Global Resource Augmentation'
        | 'Freelancer Marketplace'
        | 'Tryvion Learning Platform (TLP)'
        | 'Inside TLP - SAP Learning'
        | 'Corporate Learning - Change & Adoption'
        | 'Leadership Development'
        | 'SAP Run in the New'
        | 'Cloud Operations'
        | 'Application Support'
      )
    | null;
  /**
   * Business requirement or enquiry submitted by the visitor.
   */
  message: string;
  /**
   * Visitor confirmed the applicable TRYVION privacy notice/consent statement.
   */
  privacyConsent: boolean;
  /**
   * Timestamp recorded when privacy consent was accepted.
   */
  privacyConsentAt?: string | null;
  /**
   * Optional consent to receive TRYVION marketing/newsletter communications.
   */
  newsletterOptIn?: boolean | null;
  status: 'new' | 'in_progress' | 'contacted' | 'qualified' | 'closed' | 'spam';
  /**
   * Origin of the submission.
   */
  source?: string | null;
  submittedAt?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Formal RFP / Request a Proposal submissions received through the TRYVION website.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "rfp-submissions".
 */
export interface RfpSubmission {
  id: number;
  /**
   * Legal name of the organisation submitting the proposal request.
   */
  organisationLegalName: string;
  /**
   * Official organisation website.
   */
  organisationWebsite: string;
  industrySector:
    | 'Consumer Products'
    | 'Retail'
    | 'Fashion'
    | 'Wholesale & Distribution'
    | 'Life Sciences'
    | 'Agribusiness'
    | 'Financial Services'
    | 'Banking'
    | 'Insurance'
    | 'Public Sector'
    | 'Healthcare'
    | 'Education & Research'
    | 'Defence & Security'
    | 'Industrial Manufacturing'
    | 'High Tech'
    | 'Automotive'
    | 'Aerospace & Defence'
    | 'Energy & Utilities'
    | 'Mining'
    | 'Chemicals'
    | 'Oil & Gas'
    | 'Construction & Operations'
    | 'Commercial Real Estate'
    | 'Sports & Entertainment'
    | 'Travel & Leisure'
    | 'Professional Services'
    | 'Other';
  /**
   * Country where the organisation is headquartered.
   */
  headquartersCountry: string;
  /**
   * Primary country or regional market relevant to this opportunity.
   */
  primaryOperatingMarket: string;
  organisationSize:
    | '1–499 employees'
    | '500–4,999 employees'
    | '5,000–24,999 employees'
    | '25,000–49,999 employees'
    | '50,000+ employees';
  businessFunction:
    | 'Executive / Leadership'
    | 'IT / Technology'
    | 'Digital Transformation'
    | 'Finance'
    | 'Procurement'
    | 'Operations'
    | 'Human Resources'
    | 'Supply Chain'
    | 'Sales / Commercial'
    | 'Strategy'
    | 'Other';
  proposalContactName: string;
  proposalContactRole: string;
  procurementInvolvement:
    | 'Procurement Lead'
    | 'Business Sponsor'
    | 'Technology / IT Lead'
    | 'Transformation Lead'
    | 'Project / Programme Manager'
    | 'Executive Decision Maker'
    | 'Procurement + Business Sponsor'
    | 'Other';
  proposalContactEmail: string;
  proposalContactPhone?: string | null;
  initiativeName: string;
  transformationObjective: string;
  businessChallenge: string;
  desiredOutcomes: string;
  primaryCapability:
    | 'SAP S/4HANA'
    | 'SAP SuccessFactors'
    | 'SAP Business Technology Platform (BTP)'
    | 'SAP Ariba'
    | 'SAP Customer Experience'
    | 'Enterprise AI Strategy'
    | 'Enterprise AI Platforms'
    | 'Intelligent Automation'
    | 'Data & Analytics'
    | 'Cloud Transformation'
    | 'Enterprise Integration'
    | 'Digital Engineering'
    | 'SAP Talent Solutions'
    | 'Permanent Hiring'
    | 'Executive Search'
    | 'TRYVION Academy / Learning'
    | 'Managed Services / SAP Run in the New'
    | 'Business Transformation'
    | 'Multiple / Cross-Capability'
    | 'Other';
  secondaryCapabilities?:
    | (
        | 'SAP S/4HANA'
        | 'SAP SuccessFactors'
        | 'SAP Business Technology Platform (BTP)'
        | 'SAP Ariba'
        | 'SAP Customer Experience'
        | 'Enterprise AI Strategy'
        | 'Enterprise AI Platforms'
        | 'Intelligent Automation'
        | 'Data & Analytics'
        | 'Cloud Transformation'
        | 'Enterprise Integration'
        | 'Digital Engineering'
        | 'SAP Talent Solutions'
        | 'Permanent Hiring'
        | 'Executive Search'
        | 'TRYVION Academy / Learning'
        | 'Managed Services / SAP Run in the New'
        | 'Business Transformation'
        | 'Multiple / Cross-Capability'
        | 'Other'
      )[]
    | null;
  affectedFunctions: (
    | 'Finance'
    | 'Procurement'
    | 'Supply Chain'
    | 'Manufacturing'
    | 'Sales'
    | 'Marketing'
    | 'Customer Service'
    | 'Human Resources'
    | 'IT / Technology'
    | 'Data & Analytics'
    | 'Cybersecurity'
    | 'Operations'
    | 'Legal / Compliance'
    | 'Strategy / Transformation Office'
    | 'Executive / Corporate Functions'
    | 'Multiple / Enterprise-Wide'
    | 'Other'
  )[];
  /**
   * Countries or regions where the proposed solution will be delivered or used.
   */
  targetGeography: string;
  /**
   * Estimated number of users or stakeholders affected by the initiative.
   */
  estimatedUserCount?: number | null;
  deploymentScale?:
    | (
        | 'Single Business Unit'
        | 'Single Country'
        | 'Multiple Countries'
        | 'Regional'
        | 'Global'
        | 'Enterprise-Wide'
        | 'Not Yet Determined'
      )
    | null;
  transformationStage:
    | 'Exploring / Early Discovery'
    | 'Business Case Development'
    | 'Requirements Definition'
    | 'Solution Evaluation'
    | 'RFI / Market Research'
    | 'RFP / Tender Preparation'
    | 'RFP / Tender Issued'
    | 'Vendor Shortlisting'
    | 'Final Evaluation'
    | 'Contract / Commercial Negotiation'
    | 'Implementation Planning'
    | 'Existing Programme / Transformation'
    | 'Optimisation / Managed Services'
    | 'Not Yet Determined';
  scopeOfWork: string;
  expectedDeliverables: string;
  functionalRequirements?: string | null;
  technicalRequirements?: string | null;
  integrationRequirements?: string | null;
  dataMigrationRequirements?: string | null;
  securityComplianceRequirements?: string | null;
  reportingRequirements?: string | null;
  serviceLevelRequirements?: string | null;
  existingTechnologyStack?:
    | (
        | 'SAP'
        | 'Oracle'
        | 'Microsoft'
        | 'Salesforce'
        | 'Workday'
        | 'ServiceNow'
        | 'AWS'
        | 'Microsoft Azure'
        | 'Google Cloud'
        | 'Snowflake'
        | 'Databricks'
        | 'Other'
        | 'None / Greenfield'
      )[]
    | null;
  existingTechnologyLandscape?: string | null;
  constraintsDependencies?: string | null;
  successMeasures?: string | null;
  procurementReference?: string | null;
  rfpReference?: string | null;
  procurementStage:
    | 'Internal Requirement Identified'
    | 'Business Case Approved'
    | 'Market Research / RFI'
    | 'RFP / RFQ Preparation'
    | 'RFP / RFQ Issued'
    | 'Vendor Evaluation'
    | 'Shortlisting'
    | 'Commercial Negotiation'
    | 'Final Approval'
    | 'Award Pending'
    | 'Direct Procurement / No Formal Tender'
    | 'Not Yet Determined';
  proposalDeadline?: string | null;
  expectedAwardDate?: string | null;
  expectedStartDate?: string | null;
  engagementDuration?:
    | (
        | 'Less than 3 months'
        | '3–6 months'
        | '6–12 months'
        | '12–24 months'
        | '24+ months'
        | 'Ongoing / Managed Service'
        | 'Not Yet Determined'
      )
    | null;
  commercialModel?:
    | (
        | 'Fixed Price'
        | 'Time & Materials'
        | 'Managed Services'
        | 'Subscription / Recurring'
        | 'Outcome-Based'
        | 'Milestone-Based'
        | 'Hybrid'
        | 'Not Yet Determined'
      )
    | null;
  budgetRange?:
    | (
        | 'Not Yet Determined'
        | 'Under USD 50K'
        | 'USD 50K – 250K'
        | 'USD 250K – 1M'
        | 'USD 1M – 5M'
        | 'USD 5M+'
        | 'Prefer Not to Disclose'
      )
    | null;
  /**
   * Currency expected for the proposal, preferably ISO 4217 code such as USD or EUR.
   */
  proposalCurrency?: string | null;
  contractingEntityCountry?: string | null;
  deliveryModel?:
    ('Onsite' | 'Remote' | 'Hybrid' | 'Global Delivery' | 'Regional Delivery' | 'Not Yet Determined') | null;
  deliveryLocations?: string | null;
  documents?:
    | {
        documentType:
          | 'RFP / RFQ'
          | 'Statement of Work'
          | 'Technical Requirements'
          | 'Commercial / Pricing Schedule'
          | 'Architecture / Process Documentation'
          | 'Business Requirements'
          | 'Existing Solution Documentation'
          | 'Supporting Document'
          | 'Other';
        documentDescription?: string | null;
        fileName: string;
        blobPathname: string;
        blobUrl: string;
        contentType: string;
        fileSize: number;
        etag?: string | null;
        uploadedAt: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Required: acknowledgement that TRYVION may use the submitted information to evaluate and respond to this proposal request.
   */
  privacyConsent: boolean;
  /**
   * Optional consent to receive relevant TRYVION services, insights and future opportunities.
   */
  marketingConsent?: boolean | null;
  consentTimestamp?: string | null;
  consentVersion?: string | null;
  privacyPolicyVersion?: string | null;
  /**
   * Unique identifier assigned to the RFP submission.
   */
  submissionId?: string | null;
  formType?: string | null;
  sourceUrl?: string | null;
  sourcePage?: string | null;
  landingPage?: string | null;
  referrerUrl?: string | null;
  utmSource?: string | null;
  utmMedium?: string | null;
  utmCampaign?: string | null;
  utmTerm?: string | null;
  utmContent?: string | null;
  serviceContext?: string | null;
  industryContext?: string | null;
  locale?: string | null;
  userAgent?: string | null;
  submissionStatus?:
    | (
        | 'New'
        | 'Under Review'
        | 'Qualified'
        | 'Proposal in Preparation'
        | 'Proposal Submitted'
        | 'Won'
        | 'Lost'
        | 'On Hold'
        | 'Disqualified'
      )
    | null;
  leadPriority?: ('Low' | 'Medium' | 'High' | 'Critical') | null;
  leadScore?: number | null;
  qualificationStatus?:
    ('Not Reviewed' | 'Pending Qualification' | 'Qualified' | 'Unqualified' | 'Needs More Information') | null;
  assignedOwner?: string | null;
  assignedTeam?: string | null;
  market?: string | null;
  salesRegion?: string | null;
  accountStatus?:
    | ('Prospect' | 'Existing Customer' | 'Former Customer' | 'Strategic Account' | 'Partner / Alliance' | 'Unknown')
    | null;
  internalNotes?: string | null;
  followUpDate?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Sales and commercial enquiries submitted through the TRYVION Sales Enquiries page.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "sales-enquiries".
 */
export interface SalesEnquiry {
  id: number;
  /**
   * Full name provided by the website visitor.
   */
  fullName: string;
  /**
   * Optional job title or role.
   */
  jobTitle?: string | null;
  /**
   * Company or organisation name.
   */
  company: string;
  /**
   * Country or region entered as free text.
   */
  countryRegion: string;
  /**
   * Business email address.
   */
  workEmail: string;
  /**
   * Commercial intent selected by the website visitor.
   */
  enquiryType:
    'Services & Solutions' | 'Commercial Enquiries' | 'Existing Opportunities' | 'Partnerships' | 'General Enquiries';
  /**
   * Optional international telephone number.
   */
  phone?: string | null;
  /**
   * Business requirement, question, or commercial enquiry.
   */
  message: string;
  /**
   * Mandatory privacy consent supplied by the website visitor.
   */
  privacyConsent: boolean;
  /**
   * Timestamp at which mandatory privacy consent was accepted.
   */
  privacyConsentAt?: string | null;
  /**
   * Optional consent to receive TRYVION insights, updates, and promotional communications.
   */
  marketingConsent?: boolean | null;
  /**
   * Honeypot anti-spam field. Genuine submissions must leave this empty.
   */
  website?: string | null;
  status: 'new' | 'in_progress' | 'contacted' | 'qualified' | 'closed' | 'spam';
  /**
   * Submission source.
   */
  source?: string | null;
  submittedAt?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Customer support requests submitted through the TRYVION Customer Support page.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "customer-support".
 */
export interface CustomerSupport {
  id: number;
  /**
   * Public-facing support ticket identifier.
   */
  ticketId: string;
  fullName: string;
  company: string;
  workEmail: string;
  phone?: string | null;
  /**
   * Primary support service area used for routing.
   */
  supportArea: 'SAP Applications' | 'AI & Automation' | 'Integration & Technology' | 'Operate' | 'Other Enquiry';
  /**
   * Priority selected by the customer based on business impact.
   */
  supportPriority: 'Low' | 'Medium' | 'High' | 'Critical / Urgent';
  /**
   * Optional customer, project, contract or reference identifier.
   */
  customerProjectReference?: string | null;
  issue: string;
  /**
   * Private Vercel Blob metadata. Files are uploaded directly to Blob and verified before the ticket is created.
   */
  attachments?:
    | {
        fileName: string;
        blobPathname: string;
        contentType: string;
        fileSize: number;
        uploadedAt: string;
        id?: string | null;
      }[]
    | null;
  privacyConsent: boolean;
  privacyConsentAt?: string | null;
  marketingConsent?: boolean | null;
  /**
   * Honeypot anti-spam field.
   */
  website?: string | null;
  /**
   * Support team selected automatically from the support area.
   */
  routingTeam: 'SAP Applications' | 'AI & Automation' | 'Integration & Technology' | 'Operate' | 'Customer Support';
  status: 'new' | 'in_progress' | 'awaiting_customer' | 'resolved' | 'closed' | 'spam';
  source?: string | null;
  submittedAt?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'insights';
        value: number | Insight;
      } | null)
    | ({
        relationTo: 'team';
        value: number | Team;
      } | null)
    | ({
        relationTo: 'contact-submissions';
        value: number | ContactSubmission;
      } | null)
    | ({
        relationTo: 'rfp-submissions';
        value: number | RfpSubmission;
      } | null)
    | ({
        relationTo: 'sales-enquiries';
        value: number | SalesEnquiry;
      } | null)
    | ({
        relationTo: 'customer-support';
        value: number | CustomerSupport;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "insights_select".
 */
export interface InsightsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  excerpt?: T;
  body?: T;
  author?: T;
  category?: T;
  publishedAt?: T;
  readTime?: T;
  image?: T;
  seo?:
    | T
    | {
        metaTitle?: T;
        metaDescription?: T;
        ogImage?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "team_select".
 */
export interface TeamSelect<T extends boolean = true> {
  name?: T;
  role?: T;
  bio?: T;
  avatar?: T;
  linkedin?: T;
  email?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contact-submissions_select".
 */
export interface ContactSubmissionsSelect<T extends boolean = true> {
  fullName?: T;
  company?: T;
  email?: T;
  phone?: T;
  mainService?: T;
  subService?: T;
  message?: T;
  privacyConsent?: T;
  privacyConsentAt?: T;
  newsletterOptIn?: T;
  status?: T;
  source?: T;
  submittedAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "rfp-submissions_select".
 */
export interface RfpSubmissionsSelect<T extends boolean = true> {
  organisationLegalName?: T;
  organisationWebsite?: T;
  industrySector?: T;
  headquartersCountry?: T;
  primaryOperatingMarket?: T;
  organisationSize?: T;
  businessFunction?: T;
  proposalContactName?: T;
  proposalContactRole?: T;
  procurementInvolvement?: T;
  proposalContactEmail?: T;
  proposalContactPhone?: T;
  initiativeName?: T;
  transformationObjective?: T;
  businessChallenge?: T;
  desiredOutcomes?: T;
  primaryCapability?: T;
  secondaryCapabilities?: T;
  affectedFunctions?: T;
  targetGeography?: T;
  estimatedUserCount?: T;
  deploymentScale?: T;
  transformationStage?: T;
  scopeOfWork?: T;
  expectedDeliverables?: T;
  functionalRequirements?: T;
  technicalRequirements?: T;
  integrationRequirements?: T;
  dataMigrationRequirements?: T;
  securityComplianceRequirements?: T;
  reportingRequirements?: T;
  serviceLevelRequirements?: T;
  existingTechnologyStack?: T;
  existingTechnologyLandscape?: T;
  constraintsDependencies?: T;
  successMeasures?: T;
  procurementReference?: T;
  rfpReference?: T;
  procurementStage?: T;
  proposalDeadline?: T;
  expectedAwardDate?: T;
  expectedStartDate?: T;
  engagementDuration?: T;
  commercialModel?: T;
  budgetRange?: T;
  proposalCurrency?: T;
  contractingEntityCountry?: T;
  deliveryModel?: T;
  deliveryLocations?: T;
  documents?:
    | T
    | {
        documentType?: T;
        documentDescription?: T;
        fileName?: T;
        blobPathname?: T;
        blobUrl?: T;
        contentType?: T;
        fileSize?: T;
        etag?: T;
        uploadedAt?: T;
        id?: T;
      };
  privacyConsent?: T;
  marketingConsent?: T;
  consentTimestamp?: T;
  consentVersion?: T;
  privacyPolicyVersion?: T;
  submissionId?: T;
  formType?: T;
  sourceUrl?: T;
  sourcePage?: T;
  landingPage?: T;
  referrerUrl?: T;
  utmSource?: T;
  utmMedium?: T;
  utmCampaign?: T;
  utmTerm?: T;
  utmContent?: T;
  serviceContext?: T;
  industryContext?: T;
  locale?: T;
  userAgent?: T;
  submissionStatus?: T;
  leadPriority?: T;
  leadScore?: T;
  qualificationStatus?: T;
  assignedOwner?: T;
  assignedTeam?: T;
  market?: T;
  salesRegion?: T;
  accountStatus?: T;
  internalNotes?: T;
  followUpDate?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "sales-enquiries_select".
 */
export interface SalesEnquiriesSelect<T extends boolean = true> {
  fullName?: T;
  jobTitle?: T;
  company?: T;
  countryRegion?: T;
  workEmail?: T;
  enquiryType?: T;
  phone?: T;
  message?: T;
  privacyConsent?: T;
  privacyConsentAt?: T;
  marketingConsent?: T;
  website?: T;
  status?: T;
  source?: T;
  submittedAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "customer-support_select".
 */
export interface CustomerSupportSelect<T extends boolean = true> {
  ticketId?: T;
  fullName?: T;
  company?: T;
  workEmail?: T;
  phone?: T;
  supportArea?: T;
  supportPriority?: T;
  customerProjectReference?: T;
  issue?: T;
  attachments?:
    | T
    | {
        fileName?: T;
        blobPathname?: T;
        contentType?: T;
        fileSize?: T;
        uploadedAt?: T;
        id?: T;
      };
  privacyConsent?: T;
  privacyConsentAt?: T;
  marketingConsent?: T;
  website?: T;
  routingTeam?: T;
  status?: T;
  source?: T;
  submittedAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings".
 */
export interface SiteSetting {
  id: number;
  announcementBar?: {
    enabled?: boolean | null;
    message?: string | null;
    ctaLabel?: string | null;
    ctaHref?: string | null;
    variant?: ('info' | 'warning' | 'success') | null;
  };
  company?: {
    name?: string | null;
    tagline?: string | null;
    email?: string | null;
    phone?: string | null;
    address?: string | null;
  };
  social?:
    | {
        platform?: ('linkedin' | 'twitter' | 'github' | 'youtube') | null;
        url?: string | null;
        /**
         * Accessible label for screen readers
         */
        label?: string | null;
        id?: string | null;
      }[]
    | null;
  cookieBanner?: {
    enabled?: boolean | null;
    message?: string | null;
  };
  /**
   * Overrides hard-coded footer legal links when populated.
   */
  legalLinks?:
    | {
        label?: string | null;
        href?: string | null;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings_select".
 */
export interface SiteSettingsSelect<T extends boolean = true> {
  announcementBar?:
    | T
    | {
        enabled?: T;
        message?: T;
        ctaLabel?: T;
        ctaHref?: T;
        variant?: T;
      };
  company?:
    | T
    | {
        name?: T;
        tagline?: T;
        email?: T;
        phone?: T;
        address?: T;
      };
  social?:
    | T
    | {
        platform?: T;
        url?: T;
        label?: T;
        id?: T;
      };
  cookieBanner?:
    | T
    | {
        enabled?: T;
        message?: T;
      };
  legalLinks?:
    | T
    | {
        label?: T;
        href?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}